services:
  mysql:
    image: mysql:8.0
    container_name: pixels_mysql_source_db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_DATABASE: pixels_realtime_crud
      MYSQL_USER: pixels
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-pixels-password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./example/sql:/var/lib/mysql-files/sql
      - ./example/tpch_data:/var/lib/mysql-files/tpch_data
      - ./example/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - mysql-root-password
      - mysql-pixels-password
    networks:
      - pixels_network

  postgres:
    image: postgres:17
    container_name: pixels_postgres_source_db
    environment:
      POSTGRES_DB: pixels_realtime_crud
      POSTGRES_USER: pixels
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./example/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./example:/example
    secrets:
      - postgres-password
    networks:
      - pixels_network

  kafka:
    image: apache/kafka:3.9.0
    container_name: pixels_kafka
    environment:
      CLUSTER_ID: pixels_kafka_01
    ports:
      - "9092:9092"
    networks:
      - pixels_network
volumes:
  mysql_data:
  postgres_data:

secrets:
  mysql-root-password:
    file: ./secrets/mysql-root-password.txt
  mysql-pixels-password:
    file: ./secrets/mysql-pixels-password.txt
  postgres-password:
    file: ./secrets/postgres-pixels-password.txt

networks:
  pixels_network:
    name: pixels_crud_network 
    driver: bridge
