services:
  # monitor
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: pixels-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./images/prometheus/prometheus_local.yml:/etc/prometheus/prometheus.yml
    networks:
      - pixels_monitor_network
    extra_hosts:
        - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.1.5
    container_name: pixels-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./images/grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DEFAULT_INSTANCE_THEME=light
    networks:
      - pixels_monitor_network
    depends_on:
      - prometheus
volumes:
  grafana-data:


networks:
  pixels_monitor_network:
    name: pixels_crud_network 
    driver: bridge
