{
 "title": "Sink Server Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "label_values(sink_table_changes_total, table)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Debezium", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rate(debezium_event_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "rate(row_event_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Transaction Total Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "targets": [
    { "expr": "sink_transactions_total", "legendFormat": "Transaction Total Count" }
   ]
  },
  {
   "title": "Transaction Per Min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 22 },
   "targets": [
    {
     "expr": "rate(sink_transactions_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sink_transactions_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table Changes Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 22 },
   "targets": [
    { "expr": "sink_table_changes_total{}", "legendFormat": "{{table}}" }
   ]
  },
  {
   "title": "Processing Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sink_processing_latency_seconds{quantile=\"0.5\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "sink_processing_latency_seconds{quantile=\"0.75\"}",
     "legendFormat": "75%"
    },
    {
     "expr": "sink_processing_latency_seconds{quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "sink_processing_latency_seconds{quantile=\"0.99\"}",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Raw Data Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sink_data_throughput_counter_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row Change Event Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(sink_row_changes_total[$__rate_interval]))",
     "legendFormat": "Row Change Event/s"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "write_latency_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Total Processing Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(operation, quantile) (total_latency_seconds)",
     "legendFormat": "{{operation}} {{quantile}} "
    }
   ]
  },
  {
   "title": "Row Operations Distribution",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sink_row_changes_total) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Index",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 39 },
   "targets": [
    { "expr": "index_service_latency_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Trans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 39 },
   "targets": [
    { "expr": "trans_service_latency_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Retina",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 39 },
   "targets": [
    { "expr": "retina_service_latency_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "RPC Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "index_service_latency_seconds_count",
     "legendFormat": "Index Request Count"
    },
    {
     "expr": "retina_service_latency_seconds_count",
     "legendFormat": "Retina Request Count"
    },
    {
     "expr": "trans_service_latency_seconds_count",
     "legendFormat": "Trans Request Count"
    }
   ]
  },
  {
   "title": "RPC Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 39 },
   "targets": [
    {
     "expr": "rate(index_service_latency_seconds_count[$__rate_interval])",
     "legendFormat": "Index Request Rate"
    },
    {
     "expr": "rate(retina_service_latency_seconds_count[$__rate_interval])",
     "legendFormat": "Retina Request Rate"
    },
    {
     "expr": "rate(trans_service_latency_seconds_count[$__rate_interval])",
     "legendFormat": "Trans Request Rate"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } }
 ]
}